### ISSUE TITLE
unity builder with Il2cpp fails on windows-latest

### ISSUE THREAD

**Issue by SimonMeysman** [game-ci/unity-actions#163] opened 2023-01-04 12:54 UTC
**Bug description**

My unity project fails to build when selecting the windows-latest or windows-2022 runner in github actions. It does work when selecting windows-2019, Here are the final lines from the log:

```
Status: Downloaded newer image for unityci/editor:windows-2022.1.24f1-windows-il2cpp-1
docker: Error response from daemon: hcsshim::CreateComputeSystem 9914b7d2f840cece5f6c3dfb4d5f4f9d202dc6848749229e952225ff114b2848: The container operating system does not match the host operating system.
Error: The process 'C:\Windows\system32\docker.exe' failed with exit code 125
```

**How to reproduce**

following is the relevant snippet from my github action
```yaml
jobs:
    buildClientWindows: 
      name: Build for Windows
      runs-on: windows-latest #[self-hosted, windows]
      strategy:
        fail-fast: false
      steps:
        - uses: actions/checkout@v3
          with:
            lfs: true
        - uses: actions/cache@v3
          with:
            path: Client/Library
            key: Library-StandaloneWindows64
            restore-keys: Library-
        - uses: game-ci/unity-builder@v2
          env:
            UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          with:
            projectPath: Client
            targetPlatform: StandaloneWindows64
```

**Expected behavior**

I would expect that a windows-2022 image runs fine on a windows-2022 system. I know I can always switch back to windows-2019 but I'm trying to switch to windows-2022 to try and debug an issue where some shaders are compiled incorrectly on github, while they are being correctly compiled on windows 10/11 systems locally. 

Please let me know if I can help by providing more information or if this is the wrong place to ask for help on this.

**Comment by AndrewKahr** [comment] 2023-01-07 06:47
It fails because the windows images are built to target windows-2019 and unfortunately docker for windows must have the image version match the host os. When initially creating the images, there were issues when using an image that targets windows-2022 (iirc the editor couldn't communicate out of the image to activate the license) so it was built for 2019 as a stop-gap to get initial windows support up and running. As annoying as it is, this isn't quite a bug as it is working as intended but work should be done to bump the images to be based on 2022 as 2019 will eventually be deprecated.

There also might need to be some work to build both 2022 and 2019 and ensure unity-builder selects the correct image as if we just upgrade the images to 2022, pipelines will break due to the os version mismatch.

**Comment by SimonMeysman** [comment] 2023-01-09 13:58
Does this mean that I will also be unable to use self-hosted (windows 10) nodes to run this github action?

**Comment by davidmfinol** [comment] 2023-02-08 16:01
I think it may be possible to use a self-hosted windows 10 runner, but I think it would require significant extra work.

**Comment by davidmfinol** [comment] 2023-12-02 00:25
`windows-latest` should now correspond to `windows-2022` , which is now supported with v4 of the actions, so closing this issue.

**Closed by davidmfinol** 2023-12-02 00:25 UTC
Labels: bug
