### ISSUE TITLE
[Feature/Bug] iOS builds are huge (750mb for a 2D sprite game) / Compression Metho

### ISSUE THREAD

**Issue by CorneliusCornbread** [game-ci/unity-actions#137] opened 2022-02-05 05:00 UTC
So I'm having this issue where my iOS builds are waaaaaaaay bigger than they should be. Doing a little bit of research suggests that the solution is to change the compression method. Looking at the documentation there's nothing on changing the compression method, could this be an option that's added?

**Comment by davidmfinol** [comment] 2022-02-05 05:38
When you make builds on your local (without using CI), are they also too big?
If so, I'd say you need to start there, by getting the right compression in your local settings.

Once your local builds are a reasonable size, you should be able to get the CI builds to match that size.
If you need help to get your CI builds to match the size of your local builds, you can share the steps you take when building locally, and we may be able to help find the corresponding CI settings to match.

**Comment by CorneliusCornbread** [comment] 2022-02-05 05:44
> When you make builds on your local (without using CI), are they also too big?
> If so, I'd say you need to start there, by getting the right compression in your local settings.
> 
> Once your local builds are a reasonable size, you should be able to get the CI builds to match that size.
> If you need help to get your CI builds to match the size of your local builds, you can share the steps you take when building locally, and we may be able to help find the corresponding CI settings to match.

So you _can_ adjust the compression? If so it should be documented.

**Comment by davidmfinol** [comment] 2022-02-05 05:58
The GameCI documentation doesn't try to document everything related to Unity (as that's obviously far too large a scope), but we do try do document any options that are relevant to CI in particular. 

I don't know for certain, since I don't know what you're doing in Unity to do your compression, but I suspect there are two potential outcomes for what you're looking to do.

Either:
A) You need to update some value in your `ProjectSettings` folder to apply the correct compression settings. GameCI would automatically pick up this value and use it without having to do any CI-specific configuration. In which case, it doesn't make sense to document it here, as that would unnecessarily increase the scope of GameCI.
OR
B) What you're looking for is a custom build option, which can be applied with the `customParameters` option which is documented here: https://game.ci/docs/github/builder#customparameters 
If `customParameters` is what you're looking for and you think it could be better documented, then please feel free to raise a PR to the documentation page to help improve it.

**Comment by webbertakken** [comment] 2022-05-22 11:50
Closing for the lack of steps to reproduce.

**Closed by webbertakken** 2022-05-22 11:50 UTC
Labels: bug, need steps to reproduce
