### ISSUE TITLE
The process '/usr/bin/docker' failed with exit code 139

### ISSUE THREAD

**Issue by Ozker24** [game-ci/unity-actions#93] opened 2021-01-23 23:19 UTC
**Bug description**

I don't really know what happends as i dont know how this actually works

**How to reproduce**

Create a Git Hub repository -> git ignore of Csharp, visual studio, unity and rider on Gitignore.io -> Download the repository -> create a 2020.1.10f1 unity 3D project -> place the git ignore on the unity project folder -> create a test -> commit ->  create the unity license secret -> create a branch -> copy the test runner of the docs and change the unity version project path and only do do this acrion on pull request -> make a change on unity in the new branch -> commit ->make a pull request -> then I wait to fail the tests

**Expected behavior**

I expect just to implement CI on my project

**Additional details**

https://github.com/Ozker24/1V1

**Comment by webbertakken** [comment] 2021-01-24 02:23
Thank you for reporting your issue with unity-test-runner @Ozker24,

To speak for your expected behaviour, I think you have mostly managed to get everything to work.

From your workflow it looks like there's an error that has been fixed in the v2-alpha version of the unity actions.

![image](https://user-images.githubusercontent.com/20756439/105619413-cc8a0c00-5df2-11eb-8d65-c4dc02780c3d.png)

We have been working hard to get that issue and a few more resolved, and ended up creating a new series of docker images for it. These images are already at version 0.8 themselves as well, and they have proven quite stable so far.

As for the bad news, we will not be resolving this issue in the old images (which are used in unity actions v1.x).

Lastly, please note that when switching to the v2 of the actions you will need to repeat the activation flow with v2 too.

**Comment by Ozker24** [comment] 2021-01-24 03:54
Thank you so much for answering so fast!

I manage to get evwrything ti work thanks of the grate documentation you made!

Where can I get the newest version of unity actions?

Also, let me suggest that if there are versions that are out-dated, indicate it clearly at the begining and link the newest version.

**Comment by webbertakken** [comment] 2021-01-24 12:16
We are working on this still. We work in iterations and not everything is completely there yet. Especially when it comes to the website and the docs.

**Closed** 2021-01-24 13:15 UTC
Labels: bug

**Comment by mob-sakai** [comment] 2021-01-25 01:00
@Ozker24 
I've seen this error before.
Please add the `-nographics` option as follows.

```
      # Configure test runner
      - uses: game-ci/unity-test-runner@v2.0-alpha-2
        id: testRunner
        with:
          unityVersion: auto
          projectPath: One_V_One
          testMode: all
          customParameters: -nographics
```

**Comment by Ozker24** [comment] 2021-01-25 08:41
Hey @mob-sakai thank you for answering me.

If tested out adding the nographics line and then create a new branch and make a pull request, same error pops ups

**Comment by mob-sakai** [comment] 2021-01-25 09:02
@Ozker24 

I checked your tests.

[Run Test #3](https://github.com/Ozker24/1V1/runs/1760527181?check_suite_focus=true) built the ptoject with `-nographics` option. The test succeeded.

[Run Test #4](https://github.com/Ozker24/1V1/runs/1760545310?check_suite_focus=true) and [Run Test #5](https://github.com/Ozker24/1V1/runs/1760587144?check_suite_focus=true) built the ptoject **without** `-nographics` option. The tests failed.

![](https://user-images.githubusercontent.com/12690315/105683801-63f87780-5f37-11eb-9ba7-62adbe5f38b2.png)

**Comment by Ozker24** [comment] 2021-01-25 10:07
Yep, it finally worked. In test 4 and 5 I didn't commit the nographics line.
Thank you so much both of you for help me out.
Whish me luck for doing the unity builder action.

**Comment by webbertakken** [comment] 2021-01-25 10:42
Cool! Good luck with the builder action!
